<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.neuromed</groupId>
    <artifactId>neuromed-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>Neuromed Parent</name>

    <modules>
        <module>configserver</module>
        <module>eurekaserver</module>
        <module>gatewayserver</module>
        <module>auth-svc</module>
        <module>appointments-svc</module>
        <module>patients-svc</module>
        <module>consultants-svc</module>
        <module>reports-svc</module>
        <module>pharmarcy-svc</module>
        <module>billing-svc</module>
        <module>documents-svc</module>
        <module>support-svc</module>
        <module>notifications-svc</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring-cloud.version>2024.0.0</spring-cloud.version>
        <spring.boot.version>3.4.1</spring.boot.version>
        <module.version>0.0.1-SNAPSHOT</module.version>
        <image.tag>n4</image.tag>
        <lombok.version>1.18.32</lombok.version>
        <otelVersion>2.11.0</otelVersion>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                        </annotationProcessorPaths>
                        <release>${java.version}</release>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                    <configuration>
                        <release>21</release>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>3.4.2</version>
                    <configuration>
                        <from>
                            <image>openjdk:21-jdk-slim</image>
                        </from>
                        <to>
                            <image>prem413/${project.artifactId}:${image.tag}</image>
                        </to>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring.boot.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
